version: "3"
services:
    sqs-app:
        container_name: sqs-app
        image: softwaremill/elasticmq-native
        ports:
            - "9324:9324"
            - "9325:9325"
    sls-app:
        container_name: sls-app
        build: .
        volumes:
            - .:/app
        ports:
            - "5000:5000"
            - "5001:5001"
            - "9282:9282"
        depends_on:
            - sqs-app
            - redis-app
        environment:
            - SLS_DEBUG=*
            - NODE_ENV=test
            - NODE_PATH=./dist/utils/:./
        command: bash -c "npm-watch watch-src-offline"
    redis-app:
        image: redis
        container_name: redis-app
        ports:
            - "9379:6379"
networks:
  default:
    external: true
    name: app_network
